### ISSUE TITLE
hi

### ISSUE THREAD

**Issue by inexcited** [rahulbasutkar04/SignLanguageRecognition#1]
I know, it’s a very strange way, but I really wanted to contact you about this project, can you please write to me by email? inexcited@gmail.com

**Comment by rahulbasutkar04** [comment]
Hello,what error you are encountering, please let me know and will try to
fix it.


rahul

**Comment by inexcited** [comment]
I did this project in the same way as in the lesson, but I’m experiencing
the same problem both with you and with me, maybe you know how to solve it?
I tried changing versions, and read similar problems on Git, but nothing
has helped yet
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.imagepro, PID: 12402
    java.lang.RuntimeException: Unable to start activity
ComponentInfo{com.example.imagepro/com.example.imagepro.CameraActivity}:
java.lang.IllegalArgumentException: Internal error: Failed to apply
delegate: Next operations are not supported by GPU delegate:
    CUSTOM TFLite_Detection_PostProcess: Operation is not supported.
    First 98 operations will run on the GPU, and the remaining 1 on the CPU.
    OpenCL library not loaded - dlopen failed: library "libOpenCL-pixel.so"
not found
    Falling back to OpenGL
    TfLiteGpuDelegate Init: No EGL error, but eglChooseConfig failed.
    TfLiteGpuDelegate Prepare: delegate is not initialized
    Node number 99 (TfLiteGpuDelegateV2) failed to prepare
        at
android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3270)
        at
android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409)
        at
android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
        at
android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at
android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at
android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
     Caused by: java.lang.IllegalArgumentException: Internal error: Failed
to apply delegate: Next operations are not supported by GPU delegate:
    CUSTOM TFLite_Detection_PostProcess: Operation is not supported.
    First 98 operations will run on the GPU, and the remaining 1 on the CPU.
    OpenCL library not loaded - dlopen failed: library "libOpenCL-pixel.so"
not found
    Falling back to OpenGL
    TfLiteGpuDelegate Init: No EGL error, but eglChooseConfig failed.
    TfLiteGpuDelegate Prepare: delegate is not initialized
    Node number 99 (TfLiteGpuDelegateV2) failed to prepare
        at
org.tensorflow.lite.NativeInterpreterWrapper.applyDelegate(Native Method)
        at
org.tensorflow.lite.NativeInterpreterWrapper.applyDelegates(NativeInterpreterWrapper.java:367)
        at
org.tensorflow.lite.NativeInterpreterWrapper.init(NativeInterpreterWrapper.java:85)
        at
org.tensorflow.lite.NativeInterpreterWrapper.<init>(NativeInterpreterWrapper.java:63)
        at org.tensorflow.lite.Interpreter.<init>(Interpreter.java:277)
        at
com.example.imagepro.objectDetectorClass.<init>(objectDetectorClass.java:62)
        at
com.example.imagepro.CameraActivity.onCreate(CameraActivity.java:79)
        at android.app.Activity.performCreate(Activity.java:7802)
        at android.app.Activity.performCreate(Activity.java:7791)
        at
android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1299)
        at
android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3245)

**Comment by rahulbasutkar04** [comment]
Ok, I'll take a look...if it solved I will ping you.

rahul

**Comment by inexcited** [comment]
Ok, thanks

**Comment by inexcited** [comment]
hi, sorry for bothering you, but it didn’t work out for you?

**Comment by rahulbasutkar04** [comment]
No man , I did not get the time..but i have an working code and application
for the same.If you want that project let me know for what purpose you need
that and we will discuss it further.Actually the code  that is pushed on
github has error regarding only the versioning of the sdk,you may need to
adjust the dependencies and version of sdk.if you want to tryout that you
just go through the gradle.build file and also if you are aware we are
utilising the tflite model to predict the signs.. so you need to have the
understanding of how we can actually run the application
,model,which libraries are required etc.

**Comment by inexcited** [comment]
I tried to make a project for study using video lessons, but I just can’t
solve the problem, so I wanted to see working applications
